In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\frien\Downloads\bestsellers with categories.csv")
df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [44]:
print(df.columns) # list of columns 
print(df.shape) # (rows, columnns)

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='object')
(550, 7)

In [45]:
df.describe()

       User Rating       Reviews       Price         Year
count   550.000000    550.000000  550.000000   550.000000
mean      4.618364  11953.281818   13.100000  2014.000000
std       0.226980  11731.132017   10.842262     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4058.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17253.250000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         550 non-null    object
 1   Author       550 non-null    object
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64
 4   Price        550 non-null    int64
 5   Year         550 non-null    int64
 6   Genre        550 non-null    object
dtypes: float64(1), int64(3), object(3)
memory usage: 30.2+ KB

In [47]:
# checking null values
df.isnull().sum()

Name           0
Author         0
User Rating    0
Reviews        0
Price          0
Year           0
Genre          0
dtype: int64

In [49]:
# removing duplicates rows
df.drop_duplicates(inplace=True) # by using inplace=true changes are made directly to the original DataFrame

In [51]:
df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [50]:
df.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='object')

In [56]:
# renaming columns 
df.rename(columns = {'Name': 'Title', 'Year': 'Publication Year', 'User Rating': 'Rating'}, inplace = True)
df.columns

Index(['Title', 'Author', 'Rating', 'Reviews', 'Price', 'Publication Year',
       'Genre'],
      dtype='object')

In [57]:
df.head()

,Title,Author,Rating,Reviews,Price,Publication Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [58]:
# coverting data types 
df['Price'] = df['Price'].astype(float)

In [59]:
df.head()

,Title,Author,Rating,Reviews,Price,Publication Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8.0,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22.0,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15.0,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6.0,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12.0,2019,Non Fiction

In [73]:
# analyzing author popularity
author_counts = df['Author'].value_counts()
author_counts.head(10)

Author
Jeff Kinney                           12
Gary Chapman                          11
Rick Riordan                          11
Suzanne Collins                       11
American Psychological Association    10
Dr. Seuss                              9
Gallup                                 9
Rob Elliott                            8
Stephen R. Covey                       7
Stephenie Meyer                        7
Name: count, dtype: int64

In [68]:
df['Genre'].value_counts()

Genre
Non Fiction    310
Fiction        240
Name: count, dtype: int64

In [91]:
ave_rating_by_genre = df.groupby('Genre')['Rating'].mean()
ave_rating_by_genre

Genre
Fiction        4.648333
Non Fiction    4.595161
Name: Rating, dtype: float64

In [98]:
df.groupby('Genre')['Rating'].sum()

Genre
Fiction        1115.6
Non Fiction    1424.5
Name: Rating, dtype: float64

In [106]:
df[df['Rating']>=4].groupby('Genre')['Rating'].value_counts().groupby('Genre').sum()

Genre
Fiction        233
Non Fiction    310
Name: count, dtype: int64

In [103]:
df.groupby('Genre')['Rating'].value_counts()

Genre        Rating
Fiction      4.8       76
             4.9       41
             4.7       34
             4.6       31
             4.5       18
             4.3       11
             4.4       10
             4.0        5
             4.1        4
             3.9        3
             4.2        3
             3.8        2
             3.3        1
             3.6        1
Non Fiction  4.6       74
             4.7       74
             4.8       51
             4.5       42
             4.4       28
             4.3       14
             4.9       11
             4.0        9
             4.2        5
             4.1        2
Name: count, dtype: int64

In [71]:
# exporting to csv file avg raiting and top author 
ave_rating_by_genre.to_csv('ave_rating_by_genre.csv')
author_counts.head(10).to_csv('top_author_counts.csv')