In [63]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv(r"C:\Users\frien\Downloads\Ecommerce Purchases")
df.head()

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82

In [7]:
# list of columns
df.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [8]:
# check data type of each columns 
df.dtypes

Address              object
Lot                  object
AM or PM             object
Browser Info         object
Company              object
Credit Card           int64
CC Exp Date          object
CC Security Code      int64
CC Provider          object
Email                object
Job                  object
IP Address           object
Language             object
Purchase Price      float64
dtype: object

In [10]:
# checking null values in df
df.isnull().sum()

Address             0
Lot                 0
AM or PM            0
Browser Info        0
Company             0
Credit Card         0
CC Exp Date         0
CC Security Code    0
CC Provider         0
Email               0
Job                 0
IP Address          0
Language            0
Purchase Price      0
dtype: int64

In [16]:
# no of rows and columns 
print(len(df.columns))
print(len(df))
print(df.shape)

14
10000
(10000, 14)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Address           10000 non-null  object
 1   Lot               10000 non-null  object
 2   AM or PM          10000 non-null  object
 3   Browser Info      10000 non-null  object
 4   Company           10000 non-null  object
 5   Credit Card       10000 non-null  int64
 6   CC Exp Date       10000 non-null  object
 7   CC Security Code  10000 non-null  int64
 8   CC Provider       10000 non-null  object
 9   Email             10000 non-null  object
 10  Job               10000 non-null  object
 11  IP Address        10000 non-null  object
 12  Language          10000 non-null  object
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB

In [20]:
df.describe() # for all values including non numeric -> df.describe(include = 'all')

        Credit Card  CC Security Code  Purchase Price
count  1.000000e+04      10000.000000    10000.000000
mean   2.341374e+15        907.217800       50.347302
std    2.256103e+15       1589.693035       29.015836
min    6.040186e+10          0.000000        0.000000
25%    3.056322e+13        280.000000       25.150000
50%    8.699942e+14        548.000000       50.505000
75%    4.492298e+15        816.000000       75.770000
max    6.012000e+15       9993.000000       99.990000

In [21]:
df.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [23]:
# highest and lowest purchase price 
print(df['Purchase Price'].max())
print(df['Purchase Price'].min())
print(df['Purchase Price'].mean())

99.99
0.0
50.347302

In [36]:
# how many have fr in their language
print(len(df[df['Language'] == 'fr']))
print()
print(df[df['Language'] == 'fr'].count())

1097

Address             1097
Lot                 1097
AM or PM            1097
Browser Info        1097
Company             1097
Credit Card         1097
CC Exp Date         1097
CC Security Code    1097
CC Provider         1097
Email               1097
Job                 1097
IP Address          1097
Language            1097
Purchase Price      1097
dtype: int64

In [40]:
df[df['Language'] == 'fr']['Language'].value_counts()

Language
fr    1097
Name: count, dtype: int64

In [41]:
df.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [43]:
df[['Job']]

                                         Job
0     Scientist, product/process development
1                          Drilling engineer
2                   Customer service manager
3                          Drilling engineer
4                                Fine artist
...                                      ...
9995                              Printmaker
9996                         Energy engineer
9997                      Veterinary surgeon
9998                Local government officer
9999                  Embryologist, clinical

[10000 rows x 1 columns]

In [95]:
# job title containing engineer and artist 
# # case = false is for making it case non-sensitive default it is truw

print(df['Job'].str.contains('engineer' and 'artist').sum())
print(df['Job'].str.contains('engineer' and 'artist', case = False).sum())
print(len(df[df['Job'].str.contains('engineer' and 'artist', case = False)]))

20
40
40

In [98]:
print(df['Job'].str.contains('engineer', case = False).sum())
print(len(df[df['Job'].str.contains('engineer', case = False)]))

984
984

In [99]:
df.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [108]:
# find email of person with ip address 132.207.160.22
df[df['IP Address'] == '132.207.160.22']['Email']

2    amymiller@morales-harrison.com
Name: Email, dtype: object

In [145]:
# how many people have mastercard as their credit card provider and made purchase above 50 
len(df[(df['CC Provider'].str.contains('mastercard', case = False)) & (df['Purchase Price']>50)])

405

In [148]:
df[(df['CC Provider'].str.contains('mastercard', case = False)) & (df['Purchase Price']>50)].count()

Address             405
Lot                 405
AM or PM            405
Browser Info        405
Company             405
Credit Card         405
CC Exp Date         405
CC Security Code    405
CC Provider         405
Email               405
Job                 405
IP Address          405
Language            405
Purchase Price      405
dtype: int64

In [149]:
df.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [156]:
# find email of person with cc no = 4664825258997302
df[df['Credit Card'] == 4664825258997302]['Email']

9992    bberry@wright.net
Name: Email, dtype: object

In [173]:
# how many purchases in am and pm 
df['AM or PM'].value_counts()

AM or PM
PM    5068
AM    4932
Name: count, dtype: int64

In [176]:
# purchases price according to am and pm 
print(df.groupby('AM or PM')['Purchase Price'].sum()) # total purchase price in am and pm
print()
print(df.groupby('AM or PM')['Purchase Price'].mean()) # avg purchase price in am and pm

AM or PM
AM    247519.87
PM    255953.15
Name: Purchase Price, dtype: float64

AM or PM
AM    50.186511
PM    50.503779
Name: Purchase Price, dtype: float64

In [177]:
df.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [189]:
# how many people have credit cards that expires in 2020
(len(df[df['CC Exp Date'].str.contains('20', case = False)]))
# or df[df['CC Exp Date'].str.contains('20', case = False)].count()

988

In [192]:
# second method of above
def fun():
    count = 0
    for date in df['CC Exp Date']:
        if date.split('/')[1] =='20':
            count += 1
    print(count)
fun()

988

In [196]:
# third method of above using lambda slicing
len(df[df['CC Exp Date'].apply(lambda x:x [3:] == '20')]) # slicing date 01/20 index as 0,1,2,3,4

988

In [220]:
# top 10 most popular email providers 
df['Email'].value_counts()

Email
leekathy@yahoo.com           2
joshua41@hotmail.com         2
christopher29@gmail.com      2
ethomas@hotmail.com          2
brownjohn@hotmail.com        2
                            ..
jamesbarnett@gomez.org       1
hernandezrobert@frank.com    1
lindseywilliams@pratt.com    1
ann28@hotmail.com            1
rachelford@vaughn.com        1
Name: count, Length: 9954, dtype: int64

In [221]:

df[df['Email'].str.contains('mail', case = False)]['Email'].value_counts()

Email
matthewwilson@gmail.com       2
michael48@gmail.com           2
david80@hotmail.com           2
hcarter@hotmail.com           2
brownjohn@hotmail.com         2
                             ..
fhenson@hotmail.com           1
owong@hotmail.com             1
jonathanbarnes@hotmail.com    1
briandavis@hotmail.com        1
tyler16@gmail.com             1
Name: count, Length: 3212, dtype: int64

In [245]:
# first method of above
list1 = []
for email in df['Email']:
    list1.append(email.split('@')[1]) # leekathy@yahoo.com index as 0@1

In [246]:
df['temp'] = list1
df.head(1)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price,temp
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14,yahoo.com

In [247]:
df['temp'].value_counts().head(10)

temp
hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
brown.com         29
johnson.com       29
davis.com         25
jones.com         25
martinez.com      19
Name: count, dtype: int64

In [248]:
# second method of above 
df['Email'].apply(lambda x:x.split('@')[1]).value_counts().head(10)

Email
hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
brown.com         29
johnson.com       29
davis.com         25
jones.com         25
martinez.com      19
Name: count, dtype: int64

In [249]:
# removing any duplicate rows
df.drop_duplicates(inplace=True) # inplace = true means change are made in df in this exact moment

In [ ]:
# removing temp column from df
df.drop('temp', axis = 1, inplace = True)
df.head(1)

In [250]:
# Completed